apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: k8s-log-demo
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File    parsers.conf
        Log_Level   debug
        
    [INPUT]
        name tail
        path /var/log/nginx/access.log
        read_from_head true
        parser nginx

    [OUTPUT]
        Name          es
        Match         *
        Host          ${FLUENT_ELASTICSEARCH_HOST}
        Port          ${FLUENT_ELASTICSEARCH_PORT}
        Index         ${FLUENT_ELASTICSEARCH_INDEX}
        Suppress_Type_Name On
        
  parsers.conf: |
    [PARSER]
        Name    nginx
        Format  regex
        Regex   ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<user_agent>[^\"]*)"
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
